### ISSUE TITLE
소수구하기

### ISSUE THREAD

**Issue by haji8-thehaji** [haji8-thehaji/lecture-csharp#35]
![image](https://github.com/haji8-thehaji/lecture-csharp/assets/143566329/af759123-59b9-4fcf-86c8-44648a1738c3)

**Comment by Toribam** [comment]
'''
using System;

public class Program
{
    public static bool IsPrimeNumber(int x)
    {
        if (x <= 1)
            return false;
        if (x == 2)
            return true;
        if (x % 2 == 0)
            return false;
        for (int i = 3; i <= Math.Sqrt(x); i += 2)
        {
            if (x % i == 0)
                return false;
        }
        return true;
    }

    public static void Main(string[] args)
    {
        Console.Write("Enter any number: ");
        int num = Convert.ToInt32(Console.ReadLine());

        if (IsPrimeNumber(num))
            Console.WriteLine(num + " is a prime number");
        else
            Console.WriteLine(num + " is NOT a prime number");
    }
}
'''

**Comment by haji8-thehaji** [comment]
```


int num = 39;

for (int i = 2; i < num; i++)
{
    if(num%i == 0)
    {
        Console.WriteLine($"{num}은 소수가 아니다.");
        break;
    }
}
```

**Comment by DongHyeok12** [comment]
static bool isPrime(int num)
{
    if (num == 1 || num == 2) return true;
    else if (num > 0)
    {
        for (int i = 2; i < num; i++)
        {
            if (num % i == 0)
            {
                return false;
            }
            else if (num == i) return true;
            else return false;
        }
    }
    else return false;
}

Console.WriteLine("소수인지아닌지 구별할 양수를 입력하시오");
int a = int.Parse(Console.ReadLine());

for (int i = 0; i < a; i++)
    if (isPrime(i) == true) { }

**Comment by DongHyeok12** [comment]
Console.WriteLine("소수인지아닌지 구별할 수를 입력하시오");
int a = int.Parse(Console.ReadLine());

if (isPrime(a) == true)
{
    Console.WriteLine("소수입니다.");
    Console.WriteLine("포함되는 소수 목록:");
    for (int i = 0; i < a; i++)
    {
        if (isPrime(i) == true)
        {
            Console.Write(i + " ");
        }
    }
    Console.WriteLine(a);
}
else
{
    Console.WriteLine("소수가 아닙니다.");
    Console.WriteLine("포함되는 소수 목록:");
    for (int i = 0; i < a; i++)
    {
        if (isPrime(i) == true)
        {
            Console.Write(i + "  ");
        }
    }
}

static bool isPrime(int num)
{
    if (num == 1 || num == 2) return true;
    else if (num > 0)
    {
        for (int i = 2; i < num; i++)
        {
            if (num % i == 0)
            {
                return false;
            }
        }
        return true;
    }
    else return false;
}
