### ISSUE TITLE
피라미드 과제 (~ 4.11)

### ISSUE THREAD

**Issue by haji8-thehaji** [haji8-thehaji/lecture-csharp#39]
조보람
윤성진
조선아
```
/* 피라미드 step 1*/
*
**
***
****
*****

/* 피라미드 step 2*/
    *
   **
  ***
 ****
*****

/* 피라미드 step 3*/
    *
   ***
  *****
 *******
*********
```

**Comment by Fakeria** [comment]
윤성진
for(int i= 1; i<=5;  i++)
{
    for (int j = 0; j < i; j++)
    {
        Console.Write("*");
    }
    Console.WriteLine();
}

for (int i = 1; i <= 5; i++)
{
    for (int j = 5; j > i; j--)
    {
        Console.Write(" ");
    }
    for (int k = 0; k < i; k++)
    {
        Console.Write("*");
    }
    Console.WriteLine();
}

for (int i = 1; i <= 5; i++)
{
    for (int j = 4; j >= i; j--)
    {
        Console.Write(" ");
    }
    for (int k = 1; k <= 2 * i - 1; k++)
    {
        Console.Write("*");
    }
    Console.WriteLine();
}
