### ISSUE TITLE
전화번호부 데이터

### ISSUE THREAD

**Issue by haji8-de** [haji8-thehaji/lecture-csharp#40]
2417340052   강동민
2417340053   김동준
2417340054   박성후
2417340055   배성우
2417340056   백서영
2417340057   윤성진
2417340058   이기영
2417340059   이주호
2417340060   정민균
2417340062   정종욱
2417340063   조보람
2417340064   조선아
2417340065   조원상
2417340066   주상민
2417340067   최동혁
2417340068   최승
2417340069   최승훈
2417340070   허태우
2417340071   황제웅

**Comment by haji8-thehaji** [comment]
https://learn.microsoft.com/ko-kr/troubleshoot/developer/visualstudio/csharp/language-compilers/read-write-text-file

**Comment by haji8-thehaji** [comment]
![image](https://github.com/haji8-thehaji/lecture-csharp/assets/143566329/596b62a1-7119-4843-951d-2d3e3ba29f41)

**Comment by haji8-thehaji** [comment]
![image](https://github.com/haji8-thehaji/lecture-csharp/assets/143566329/19adc377-cd4a-454d-81b8-bae5c85b0cce)
