### ISSUE TITLE
중간고사

### ISSUE THREAD

**Issue by haji8-thehaji** [haji8-thehaji/lecture-csharp#52]
https://www.w3schools.com/quiztest/quiztest.asp?qtest=CS

[pos기 프로그램.zip](https://github.com/haji8-thehaji/lecture-csharp/files/15052541/pos.zip)
[pos기 프로그램2.zip](https://github.com/haji8-thehaji/lecture-csharp/files/15103331/pos.2.zip)

project 폴더 내의 \bin\Debug\net8.0-windows 로 들어가면
exe 실행파일이 존재함.

해당 폴더를 압축해서 제출

---------------------

admin / 1234

1. 로그인 창에서 엔터 누를경우, 로그인 가능
2. 장바구니 담기 기능
3. 장바구니 결제, 비우기 기능
4. 필터 기능
5. 종료시 프로그램이 종료됨 ( 로그인창 숨김 으로 제대로 종료되지 않음)
6. 과일 정보 변경시, 텍스트 박스에 저장

![image](https://github.com/haji8-thehaji/lecture-csharp/assets/143566329/71e4571e-0d95-4ba5-842e-779523eeffe3)

![image](https://github.com/haji8-thehaji/lecture-csharp/assets/143566329/27516abe-9b4a-4042-ae18-bd650bef16e9)

**Comment by haji8-thehaji** [comment]
1번 c# 문제 풀고 나서, 점수 화면을 공유합니다.

윈도우 + 쉬프트+ S 키를 누르면 화면을 캡쳐할 수 있고, 캡쳐한 화면을 git에 업로드 합니다,

학번 이름을 입력하여, 댓글에 추가합니다.

2024  하지양
![image](https://github.com/haji8-thehaji/lecture-csharp/assets/143566329/455424b4-6524-4a72-bd92-5102bd1c4ce1)

**Comment by jonguk123123123** [comment]
2417340062 정종욱
![image](https://github.com/haji8-thehaji/lecture-csharp/assets/162538228/2fc08809-2bf7-4441-a821-6e9a7652e6cc)

**Comment by lky27102710** [comment]
2417340058 이기영

![스크린샷 2024-04-25 110453](https://github.com/haji8-thehaji/lecture-csharp/assets/162538348/eb0496ef-31b4-4e92-9100-227e342a9b9c)

**Comment by Fakeria** [comment]
학번 : 2417340057 이름 : 윤성진
![image](https://github.com/haji8-thehaji/lecture-csharp/assets/162538422/e8461dbb-6108-4ed4-9ea7-a8e53295f9f3)

**Comment by DongHyeok12** [comment]
2017340067 최동혁
![image](https://github.com/haji8-thehaji/lecture-csharp/assets/162538389/67fe5a99-9af0-43d4-b3fa-926eee5bc7c7)

**Comment by VRCneyu** [comment]
2417340052 강동민
![image](https://github.com/haji8-thehaji/lecture-csharp/assets/114811344/3a922460-045c-4bcc-80ba-a001cf43e629)

**Comment by nfs0301** [comment]
![image](https://github.com/haji8-thehaji/lecture-csharp/assets/89842556/9a7a72a3-038e-4aad-9e73-9dfa1f63fcfa)

**Comment by suna0000** [comment]
2417340064 조선아
![image](https://github.com/haji8-thehaji/lecture-csharp/assets/162538314/355cc978-82ed-4ce6-9893-9ab558deb294)

**Comment by Baekseoyoung** [comment]
2417340056 백서영
![스크린샷 2024-04-25 111235](https://github.com/haji8-thehaji/lecture-csharp/assets/163382630/4bc97274-ff2f-4ebe-bf3b-672b192f35d6)

**Comment by 22ooho** [comment]
학번: 2417340059       이름: 이주호
![스크린샷 2024-04-25 111221](https://github.com/haji8-thehaji/lecture-csharp/assets/162538225/73ef726b-fdfd-4497-ad03-cbd996d07910)

**Comment by Jmg123123123** [comment]
2417340060 정민균
![화면 캡처 2024-04-25 111354](https://github.com/haji8-thehaji/lecture-csharp/assets/134722931/3f3d3105-3eae-4dc5-bd3b-dfc6867ef22d)

**Comment by CS9909** [comment]
![2417340068최승](https://github.com/haji8-thehaji/lecture-csharp/assets/162538281/0cb2a0be-ebf2-4422-bce5-3c39709d6626)
2417340068최승

**Comment by ghkdwpdnd123** [comment]
2417340071

**Comment by isaga121** [comment]
2417340054 박성후
![image](https://github.com/haji8-thehaji/lecture-csharp/assets/162538378/e0008d03-677b-4b08-b73b-3292ae8c045e)

**Comment by dyek18** [comment]
2417340070   허태우
![스크린샷 2024-04-25 111324](https://github.com/haji8-thehaji/lecture-csharp/assets/147579290/64d55e10-f854-44b2-a89a-cdba771720ad)

**Comment by mungmungii** [comment]
주상민
![image](https://github.com/haji8-thehaji/lecture-csharp/assets/162538457/d693f0ae-087d-4c99-b46f-7ebc9fb34443)

**Comment by sungwoo701** [comment]
2417340055 배성우
![화면 캡처 2024-04-25 112348](https://github.com/haji8-thehaji/lecture-csharp/assets/162538496/578d8e77-c143-4696-b01d-7ff9ab09e46d)

**Comment by choboram** [comment]
2417340063 조보람
![image](https://github.com/haji8-thehaji/lecture-csharp/assets/163382595/9711a6f5-8546-4130-8eab-bb9eb5db0a5f)

**Comment by ghkdwpdnd123** [comment]
![image](https://github.com/haji8-thehaji/lecture-csharp/assets/162538968/619a6cb5-f5b2-484d-98fc-5e674936e5c8)
2417340071

**Comment by haji8-thehaji** [comment]
project 폴더 내의 \bin\Debug\net8.0-windows 로 들어가면
exe 실행파일이 존재함.

해당 폴더를 압축해서 제출
